import{a as L,S as w,i as b}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function a(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(t){if(t.ep)return;t.ep=!0;const n=a(t);fetch(t.href,n)}})();const S="47504647-de6fca25d262a81a07b30a07f",v="https://pixabay.com/api/";async function h(e,r=1,a=15){const o=`${v}?key=${S}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${a}`;try{return(await L.get(o)).data}catch(t){throw console.error("Error fetching images:",t.message),t}}let u;function m(e){const r=document.querySelector(".gallery"),a=e.map(o=>`
    <a href="${o.largeImageURL}" class="gallery__item">
      <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${o.likes}</p>
        <p><b>Views:</b> ${o.views}</p>
        <p><b>Comments:</b> ${o.comments}</p>
        <p><b>Downloads:</b> ${o.downloads}</p>
      </div>
    </a>`).join("");r.innerHTML+=a,u?u.refresh():u=new w(".gallery a",{captionDelay:250,captionsData:"alt"})}function $(){const e=document.querySelector(".gallery");e.innerHTML=""}function p(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function c(e,r="info"){b[r]({title:"Notification",message:e,position:"topRight"})}let i="",s=1,f=0;const q=document.querySelector(".search-form"),y=document.querySelector(".load-more"),E=document.querySelector(".gallery");function l(e){e?y.classList.remove("hidden"):y.classList.add("hidden")}q.addEventListener("submit",async e=>{if(e.preventDefault(),i=e.target.querySelector(".search-input").value.trim(),!!i){s=1,$(),l(!1),p();try{const r=await h(i,s);f=r.totalHits,r.hits.length===0?c("Sorry, no images found.","error"):(m(r.hits),f>s*15?l(!0):l(!1))}catch{c("Something went wrong. Please try again.","error")}finally{g()}}});y.addEventListener("click",async()=>{s+=1,p();try{const e=await h(i,s);e.hits.length===0||s*15>=f?(c("We're sorry, but you've reached the end of search results.","info"),l(!1)):(m(e.hits),I())}catch{c("Something went wrong. Please try again.","error")}finally{g()}});function I(){const e=E.lastElementChild,{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
