import{a as b,i as m,S as w}from"./assets/vendor-D0cagnvz.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&o(u)}).observe(document,{childList:!0,subtree:!0});function s(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(r){if(r.ep)return;r.ep=!0;const n=s(r);fetch(r.href,n)}})();const L="47504647-de6fca25d262a81a07b30a07f",S="https://pixabay.com/api/",y=async(e,t,s=15)=>{if(!e||typeof e!="string")throw new Error("Query must be a non-empty string");if(t<=0||typeof t!="number")throw new Error("Page must be a positive number");const o={key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s};console.log("Fetching images with params:",o);try{return(await b.get(S,{params:o})).data}catch(r){throw console.error("Error fetching images:",r.message),r}};function g(e){const t=document.querySelector(".gallery"),s=e.map(o=>`
    <a href="${o.largeImageURL}" class="gallery__item">
      <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${o.likes}</p>
        <p><b>Views:</b> ${o.views}</p>
        <p><b>Comments:</b> ${o.comments}</p>
        <p><b>Downloads:</b> ${o.downloads}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",s)}function v(){const e=document.querySelector(".gallery");e.innerHTML=""}function E(){const e=document.querySelector(".loader");e&&e.classList.remove("hidden")}function q(){const e=document.querySelector(".loader");e&&e.classList.add("hidden")}function d(e,t="info"){if(!["info","success","warning","error"].includes(t)){console.error(`Invalid notification type: ${t}`);return}m[t]({title:"Notification",message:e,position:"topRight"})}const P=document.querySelector(".search-form");document.querySelector(".search-input");const $=document.querySelector(".gallery"),p=document.querySelector(".load-more");let a,i=1,c="";const l=15;let f=0;function h(e){p.style.display=e?"block":"none"}function M(){m.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}P.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.elements.searchQuery.value.trim(),!c){d("Please enter a search query!","warning");return}v(),i=1,h(!1);try{E();const t=await y(c,i,l);f=t.totalHits,t.hits.length===0?d("Sorry, there are no images matching your search query. Please try again!","error"):(g(t.hits),a?a.refresh():a=new w(".gallery a")),f>l&&h(!0)}catch{d("Something went wrong. Please try again later!","error")}finally{q()}});p.addEventListener("click",async()=>{i+=1;try{const e=await y(c,i,l);g(e.hits,!0),a.refresh();const t=$.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),i*l>=f&&(h(!1),M())}catch(e){console.error("Error fetching images:",e)}});
//# sourceMappingURL=index.js.map
